"use client";
import Header from "@/components/Header/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import LSidebar from "@/components/Left sidebar/LSidebar";
import RSidebar from "@/components/Right sidebar/RSidebar";
import { useState } from "react";
import LogIn from "@/components/LogIn";

const inter = Roboto({ subsets: ["latin"], weight: ["500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const loggedIn = localStorage.getItem("logged");

export default function RootLayout({ children }) {
  const [isSidebarOpen, setSidebarOpen] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(loggedIn);

  const toggleSidebar = () => {
    setSidebarOpen(!isSidebarOpen);
  };
  const user = JSON.parse(localStorage.getItem("user"));
  // console.log(user);
  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoggedIn === "true" ? (
          <div className="w-full flex relative md:grid md:grid-cols-4">
            <LSidebar
              isOpen={isSidebarOpen}
              toggleSidebar={toggleSidebar}
              name={user.name}
              email={user.email}
            />
            <main className="md:col-span-3">
              <Header
                toggleSidebar={toggleSidebar}
                name={user.name}
                email={user.email}
              />
              {children}
            </main>
            {/* <RSidebar /> */}
          </div>
        ) : (
          <LogIn setIsLoggedIn={setIsLoggedIn} isLoggedIn={isLoggedIn} />
        )}
      </body>
    </html>
  );
}
